### PR TITLE
Configurations of Database

### PR DESCRIPTION
**Pull request by Christian-Ishimwe**
I added the Configurations of Database, where we will use the Postgress Database and sequelize.
For getting started, since the database if hosted locally,  for getting started we will be required to  install Pgadmin locally to use the postgress Database, and after we create a database within pgadmin where we will have the DATABASE_NAME, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST to set within the .env file.

### CODE REVIEW

**Comment by Christian-Ishimwe** [comment]
@ka-lili Please review this

**Review by igorihimbazwe — COMMENTED** [review]
good

**Review by lilika67 — APPROVED** [review]

**Review by igorihimbazwe — APPROVED** [review]

**Review by igorihimbazwe — COMMENTED** [review]
resolve the conflict on package json

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
@Christian-Ishimwe please do the following:
1. Rebase to `develop` branch
2. Remove the conflicts
3. Add a descriptive details of your PR (use the example in these slides)
4. Change the commit message i.e "[Delivers #storyID] adding database configurations". Refer to [this](https://www.pivotaltracker.com/help/articles/github_integration/)
5. We are using TypeScript that is what we agreed on!

**Comment by pacifiquemboni** [comment]
refer to fx-create-empty-repo branch created by Celestin to configure Database

**Pull request closed without merging**
