### PR TITLE
[finishes #187355082] Set up an empty Express Boilerplate with dotenv

### PR DESCRIPTION
**Pull request by pacifiquemboni**
What does this PR do?
Set up an empty Express Boilerplate with dotenv

Description of task to be completed
Set up an empty Node.js - express application.
By this We mean a full directory with all folders that you think developer will need. this might include but not limited to
src/ controllers, models, routes helpers,validations, etc.

relevant pivotal tracker stories
https://www.pivotaltracker.com/story/show/187355082

### CODE REVIEW

**Comment by Celestin4** [comment]
You have to add .env in gitignore. Then share us .env.example as template for env format

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
@pacifiquemboni please add:
- The folders of models, validations, controllers, etc
- The commit message should be `[Finishes #187355082] Set up ....`
- Please remove `.env` from the committed file and add `.env.example` and `.gitignore` file
- Remove dist folder and add it in `.gitignore` file

**Review by UmuhireJessie — APPROVED** [review]

**Comment by Celestin4** [comment]
Nodemon is installed but there in no script to restart the server when it crashes or on new changes

**Comment by pacifiquemboni** [comment]
> Nodemon is installed but there in no script to restart the server when it crashes or on new changes
added nodemon on start script

**Review by lilika67 — APPROVED** [review]

**Review by ka-lili — APPROVED** [review]

**Pull request merged**
