### PR TITLE
[Finishes  #187355092]  Deploy base application to render

### PR DESCRIPTION
**Pull request by jniyonkuru**
What does this PR do?
Configure ci/cd pipeline for the project
Description of Task to be completed?
This task was to set up ci/cd  pipeline ,hosting the app on render and reflect every user pull request in the review app
How should this be manually tested?
create a pull request and the recommended changes will be reflected into the app hosted on render
Any background context you want to provide?
What are the relevant pivotal tracker?
Deploy base application to render or cyclic,#187355092

### CODE REVIEW

**Review by pacifiquemboni — COMMENTED** [review]
Change the commit message i.e "[Delivers #storyID] create deploy.yml".
All checks didnot pass successfull, work on that

**Comment by jniyonkuru** [comment]
@pacifiquemboni can  you review again

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Good @jniyonkuru, please add:
1. Link of render where the application is hosted in readme file and in about of the github repository
2. If the deployment was successful, we should access the app via the link provided on either PR or on `develop` branch

**Review by lilika67 — APPROVED** [review]

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Resolve the conflicts

**Review by UmuhireJessie — APPROVED** [review]

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
@jniyonkuru can you squash the commits

**Review by pacifiquemboni — APPROVED** [review]

**Comment by pacifiquemboni** [comment]
@jniyonkuru if you worked on requested changes re-request review to the one who requested those changes so the he/she can confirm if the issue is solved.

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
